- include_vars:
    file: "../vars/main.yml"
  
- name: az_cli
  # shell: az account list
  shell: |
    az account set --subscription {{ subscription }}
    az account show
    # az account list
  register: output

- debug: var=output.stdout_lines

- name: Get Azure Cache for Redis with access keys by name
  azure_rm_rediscache_info:
    resource_group: '{{ resource_group_name }}'
    name: '{{ redis_db_name }}'
    return_access_keys: true
  register: rdb
  async: 1000
  poll: 0

# will only show the trace of the async task
- debug:
    var: rdb
    
- name: Get instance of Database Account
  azure_rm_cosmosdbaccount_info:
    resource_group: '{{ resource_group_name }}'
    name: '{{ cosmos_db_account_name }}'
    retrieve_connection_strings: true
  register: db
  async: 1000
  poll: 0

- name: Get facts for one account
  azure_rm_storageaccount_info:
    resource_group: '{{ resource_group_name }}'
    name: '{{ storage_account_name }}'
    show_connection_string: true
  register: sa
  async: 1000
  poll: 0

- name: Get instance of Registry
  azure_rm_containerregistry_info:
    resource_group: '{{ resource_group_name }}'
    name: '{{ acr_name }}'
    retrieve_credentials: true
  register: acr
  async: 1000
  poll: 0
  
- name: Wait for gets
  async_status:
    jid: '{{ item }}'
  register: wait
  until: wait.finished
  retries: 10
  with_items: 
    - '{{ rdb.ansible_job_id }}'
    - '{{ db.ansible_job_id }}'
    - '{{ sa.ansible_job_id }}'
    - '{{ acr.ansible_job_id }}'

# - debug:
#     var: wait.results
- debug: 
    msg: '{{ wait.results[0].rediscaches[0].host_name }} {{ wait.results[0].rediscaches[0].access_keys.primary }}'
- debug:
    msg: '{{ wait.results[1].accounts[0].connection_strings.connection_strings[0].connection_string }}'
- debug:
    msg: '{{ wait.results[2].storageaccounts[0].primary_endpoints.blob.connectionstring.split("AccountKey=")[-1].split(";")[0] }}'
- debug:
    msg: '{{ wait.results[3].registries[0].credentials.username }} {{ wait.results[3].registries[0].credentials.password }} {{ wait.results[3].registries[0].login_server }}'

- name: Create backend container group
  azure_rm_containerinstance:
    resource_group: '{{ resource_group_name }}'
    name: '{{ backend_container_group_name }}'
    location: '{{ location }}'
    os_type: linux
    ip_address: public

    containers:
      - name: '{{ backend_container_name }}'
        image: '{{ wait.results[3].registries[0].login_server }}/{{ backend_image }}'
        cpu: 0.5
        memory: 4

        environment_variables:
          - name:  MONGO_URL 
            is_secure: false
            value: '{{ wait.results[1].accounts[0].connection_strings.connection_strings[0].connection_string }}'
          - name:  REDIS_HOST 
            is_secure: false
            value: '{{ wait.results[0].rediscaches[0].host_name }}'
          - name:  REDIS_PORT 
            is_secure: false
            value: 6380
          - name:  REDIS_PASS 
            is_secure: false
            value: '{{ wait.results[0].rediscaches[0].access_keys.primary }}'
          - name:  STORAGE_ACCOUNT_NAME 
            is_secure: false
            value: '{{ storage_account_name }}'
          - name:  STORAGE_CONTAINER_NAME 
            is_secure: false
            value: '{{ storage_container_name }}'
          - name:  STORAGE_ACCOUNT_KEY 
            is_secure: false
            value: '{{ wait.results[2].storageaccounts[0].primary_endpoints.blob.connectionstring.split("AccountKey=")[1].split(";")[0] }}'

        ports:
          - 4000

    registry_username: '{{ wait.results[3].registries[0].credentials.username }}'
    registry_password: '{{ wait.results[3].registries[0].credentials.password }}' 
    registry_login_server: '{{ wait.results[3].registries[0].login_server }}'
  register: acib

- debug:
    var: acib