- name: Provision the project's resources and build docker images
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: destroy
      tags: ['destroy']

    - role: infra-base
      tags: ['base']

    - role: docker
      tags: ['docker', 'backend']
      vars:
        targetimage: backend

    - role: backend
      tags: ['backend']

    - role: docker
      tags: ['docker', 'frontend']
      vars:
        targetimage: frontend

    - role: frontend
      tags: ['frontend']