- hosts: localhost
  connection: local
# - hosts: local
  

  tasks:
    - name: az_cli
      # shell: az account list
      shell: |
        az account set --subscription 
        az account show
        # az account list
      register: output
    - debug: var=output.stdout_lines

    - name: Create a resource group in azure
      azure_rm_resourcegroup:
        name: rg-gb-prueba-poc-3
        location: westeurope
        auth_source: cli
      register: rg
    - debug:
        var: rg

    