- include_vars:
    file: "../vars/main.yml"
  
- name: az_cli
  # shell: az account list
  shell: |
    az account set --subscription {{ subscription }}
    az account show
    # az account list
  register: output

- debug: var=output.stdout_lines

# - name: where am i
#   # shell: az account list
#   shell: | 
#     pwd
#     ls -lah
#     ls -lah '../../terraform'
#   register: output

# - debug:
#     var: output

- name: Deployment of base project
  community.general.terraform:
    project_path: '../../{{ targetproject }}'
    variables_files: 'variables.tfvars'
    state: present
    force_init: true
  register: tfoutput

- debug:
    var: tfoutput